# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "sinatra-contrib", "~> 4.0"
gem "puma", "~> 6.0"
gem "sqlite3", "~> 2.0"
gem "rack-cors", "~> 2.0"
gem "rackup", "~> 2.0"
