packages:
  - editors/*
  - integrations/astro-alap
  - integrations/eleventy-alap
  - integrations/next-alap
  - integrations/nuxt-alap
  - integrations/qwik-alap
  - plugins/mdx
  - plugins/rehype-alap
  - plugins/remark-alap
  - plugins/tiptap-alap
  - examples/sites/astro-integration
  - examples/sites/eleventy
  - examples/sites/tiptap
  - examples/servers/*
