/**
 * Copyright 2026 Daniel Smith
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Seed site rules for the Alap editor metadata system.
// These are loaded into IndexedDB on first use.
// Ported from TTT's PostgreSQL site_rules table.

import type { SiteRule } from './meta-rules';

export const SEED_RULES: SiteRule[] = [
  // --- html_scrape ---
  {
    domain: 'cnn.com',
    strategy: 'html_scrape',
    strategyConfig: null,
    title: ['og_title', 'twitter_title', 'title_tag'],
    description: ['og_description', 'twitter_description', 'meta_description'],
    authors: ['article_author', 'meta_author'],
    thumbnail: ['og_images', 'twitter_image'],
    canonicalUrl: ['canonical_url'],
    locale: ['og_locale'],
    publishedDate: ['article_published_time', 'date'],
    modifiedDate: ['article_modified_time'],
    latitude: ['place_latitude'],
    longitude: ['place_longitude'],
    placeName: ['geo_placename'],
    tags_from: ['meta_section', 'og_type', 'og_site_name'],
    tags_skip: ['meta_keywords', 'article_tags'],
    tag_hostname: true,
  },
  {
    domain: 'huffpost.com',
    strategy: 'html_scrape',
    strategyConfig: null,
    title: ['og_title', 'title_tag'],
    description: ['og_description', 'meta_description'],
    authors: ['article_author', 'meta_author'],
    thumbnail: ['og_images', 'twitter_image'],
    canonicalUrl: ['canonical_url'],
    locale: ['og_locale'],
    publishedDate: ['article_published_time', 'date'],
    modifiedDate: ['article_modified_time'],
    latitude: ['place_latitude'],
    longitude: ['place_longitude'],
    placeName: ['geo_placename'],
    tags_from: [
      'article_tags', 'article_section', 'meta_keywords',
      'og_site_name', 'og_type', 'og_locale',
    ],
    tags_skip: [],
    tag_hostname: true,
  },
  // --- json_api ---
  {
    domain: 'reddit.com',
    strategy: 'json_api',
    strategyConfig: {
      jsonUrlTransform: '${url}.json',
      jsonPath: {
        title: '0.data.children.0.data.title',
        og_images: '0.data.children.0.data.thumbnail',
        subreddit: '0.data.children.0.data.subreddit',
        meta_author: '0.data.children.0.data.author',
        meta_description: '0.data.children.0.data.selftext',
      },
    },
    title: ['title'],
    description: ['meta_description'],
    authors: ['meta_author'],
    thumbnail: ['og_images'],
    canonicalUrl: [],
    locale: [],
    publishedDate: [],
    modifiedDate: [],
    latitude: [],
    longitude: [],
    placeName: [],
    tags_from: ['subreddit', 'meta_author'],
    tags_skip: [],
    tag_hostname: true,
  },
  // --- oembed ---
  {
    domain: 'youtube.com',
    strategy: 'oembed',
    strategyConfig: { oembedUrl: 'https://www.youtube.com/oembed?url=${url}&format=json' },
    title: ['oembed_title'],
    description: [],
    authors: ['oembed_author'],
    thumbnail: ['oembed_thumbnail'],
    canonicalUrl: [],
    locale: [],
    publishedDate: [],
    modifiedDate: [],
    latitude: [],
    longitude: [],
    placeName: [],
    tags_from: ['oembed_author'],
    tags_skip: [],
    tag_hostname: true,
  },
  {
    domain: 'twitter.com',
    strategy: 'oembed',
    strategyConfig: { oembedUrl: 'https://publish.twitter.com/oembed?url=${url}' },
    title: ['oembed_title'],
    description: [],
    authors: ['oembed_author'],
    thumbnail: ['oembed_thumbnail'],
    canonicalUrl: [],
    locale: [],
    publishedDate: [],
    modifiedDate: [],
    latitude: [],
    longitude: [],
    placeName: [],
    tags_from: ['oembed_author'],
    tags_skip: [],
    tag_hostname: true,
  },
  {
    domain: 'x.com',
    strategy: 'oembed',
    strategyConfig: { oembedUrl: 'https://publish.twitter.com/oembed?url=${url}' },
    title: ['oembed_title'],
    description: [],
    authors: ['oembed_author'],
    thumbnail: [],
    canonicalUrl: [],
    locale: [],
    publishedDate: [],
    modifiedDate: [],
    latitude: [],
    longitude: [],
    placeName: [],
    tags_from: ['oembed_author'],
    tags_skip: [],
    tag_hostname: true,
  },
  {
    domain: 'tiktok.com',
    strategy: 'oembed',
    strategyConfig: { oembedUrl: 'https://www.tiktok.com/oembed?url=${url}' },
    title: ['oembed_title'],
    description: [],
    authors: ['oembed_author'],
    thumbnail: ['oembed_thumbnail'],
    canonicalUrl: [],
    locale: [],
    publishedDate: [],
    modifiedDate: [],
    latitude: [],
    longitude: [],
    placeName: [],
    tags_from: ['oembed_author'],
    tags_skip: [],
    tag_hostname: true,
  },
  {
    domain: 'spotify.com',
    strategy: 'oembed',
    strategyConfig: { oembedUrl: 'https://open.spotify.com/oembed?url=${url}' },
    title: ['oembed_title'],
    description: [],
    authors: ['oembed_author'],
    thumbnail: ['oembed_thumbnail'],
    canonicalUrl: [],
    locale: [],
    publishedDate: [],
    modifiedDate: [],
    latitude: [],
    longitude: [],
    placeName: [],
    tags_from: ['oembed_author'],
    tags_skip: [],
    tag_hostname: true,
  },
  {
    domain: 'vimeo.com',
    strategy: 'oembed',
    strategyConfig: { oembedUrl: 'https://vimeo.com/api/oembed.json?url=${url}' },
    title: ['oembed_title'],
    description: [],
    authors: ['oembed_author'],
    thumbnail: ['oembed_thumbnail'],
    canonicalUrl: [],
    locale: [],
    publishedDate: [],
    modifiedDate: [],
    latitude: [],
    longitude: [],
    placeName: [],
    tags_from: ['oembed_author'],
    tags_skip: [],
    tag_hostname: true,
  },
];
